### SIGNUP create user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "username": "Andreaaaaa",
  "password": "12341234"
}


### SIGNIN
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "username": "BBBrain",
  "password": "skopdddal"
}

### find user by token
GET http://localhost:3000/auth/me
Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YjA5YzFkMjcxYzhmNmFlMWRlZjExNiIsInVzZXJuYW1lIjoiQkJCcmFpbiIsImlhdCI6MTc0MDEyNzMyMSwiZXhwIjoxNzQwMTMwOTIxfQ._lo0zHKyzzO4nWd_pqsnHrMescVbrVBohyRUwtkMO9c
