### getAllUser
GET http://localhost:3000/users

### getUserByUsername
POST http://localhost:3000/users/search
Content-Type: application/json

{
  "username": "Annie"
}

### deleteUserById
DELETE http://localhost:3000/users/67b063a3dac8d63a0a25c2d0































